### ISSUE TITLE
AP-1858: Name will be cutoff at bottom of chat if the name includes "||" in it 

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Core-PWA#3737]
**Device:**Desktop, Mobile (Android & iOS)

**Browser:**Chrome, Brave, Safari, Opera

**Issue:**When I use the name “ Phil ||Satellite.im“ when I go into chat and my name appears at the bottom it will only show as “ Phil “

**How to replicate:**

Create a new account

Make name “ Whatever || whatever youd like “

Navigate to chat

At bottom you will appear as Whatever

**Screenshot:**
[file id="f81e70cd-9663-4d2a-9727-a4d6c629cc80"]

**Comment by stavares843** [comment]
> Sara Tavares commented in Jira:

moved to To Do because PR was closed

**Comment by stavares843** [comment]
> Sara Tavares commented in Jira:

reporter: Phillip Wisniewski

**Comment by stavares843** [comment]
@phillsatellite can you retest pls? 🔨

**Comment by phillsatellite** [comment]
tested when user uses pipes it will appear twice in the bottom of chat when user is typing. Created ticket here https://satellite-im.atlassian.net/browse/AP-2585?atlOrigin=eyJpIjoiNDcwYjk0NDk5MzkwNGIyNmFiYTI2ZjUzYTA4NDdlNTMiLCJwIjoiaiJ9
