### ISSUE TITLE
AP-1876: chat files - determine size limit and whether it counts towards your upload total

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Core-PWA#3780]

**Comment by stavares843** [comment]
@josephmcg @molimauro  do we still need this?

**Comment by josephmcg** [comment]
yeah this is more of an executive decision.

I think it would create an unpleasant user experience if messages contribute to the limit, but then there's not much of an incentive to buy additional storage space. The user can just make two accounts and send things to themselves for free
