### ISSUE TITLE
AP-1878: replace simplescroll implementations with css

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Core-PWA#3784]
more lightweight and easier to style. mostly done

**Comment by stavares843** [comment]
> Sara Tavares commented in Jira:

moved to To Do because PR was closed

**Comment by stavares843** [comment]
@josephmcg @molimauro  do we still need this?

**Comment by josephmcg** [comment]
There's a handful of them in un-rendered, legacy components. I'll finish it up
