### ISSUE TITLE
AP-1921: [Vue warn]: Invalid prop: type check failed for prop "scrollTopOnChange". Expected String, Boolean, got Number with value 1.

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Core-PWA#3869]
STR:

go to chat

search

returns error on console

[file id="fed0f272-84fe-47f4-a312-6444a4c7779c"]

**Comment by stavares843** [comment]
do we still need this? @josephmcg @molimauro

**Comment by molimauro** [comment]
releated to simplescroll, will close
