### ISSUE TITLE
AP-1925: Chat will jump to bottom if user scrolls up too fast 

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Core-PWA#3873]
**Device:**Desktop

**Browser:**Chrome, Brave

**Issue:**If you go to chat and immediately scroll to the top, it will jump to the bottom

**How to replicate:**

Enter chat

Immediately scroll to the top of chat

Chat will jump to bottom

**Screen recording:**
[file id="058d8e28-bf80-4162-9dd4-cb5894774199"]

**Comment by stavares843** [comment]
> Sara Tavares commented in Jira:

reporter: Phillip Wisniewski

**Comment by jasonwoodland** [comment]
@stavares843 can't reproduce, chat scroll has had a lot of work done since this report. I think we can close this one

**Comment by stavares843** [comment]
agree
