### ISSUE TITLE
AP-2011: More Wallets! 

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Core-PWA#4045]
Integrate other Wallets based on those available in Solana \ Wallet Adapter

**Comment by stavares843** [comment]
> Nicholas Zaccagnino commented in Jira:

Implementing just the Solana-labs supported wallets, opening a new task for the other wallets

**Comment by aewing** [comment]
this seems like a duplicate

**Comment by JustZacca** [comment]
@aewing 
There are 2 versions of the same Task

More Wallets = Which only covers Solana Wallets
#4294](https://github.com/Satellite-im/Core-PWA/issues/4294) = Which covers Metamask and Wallet Connect

The tasks have been split since the Solana wallets were ready, but the others not
