### ISSUE TITLE
AP-2214: switch call display layout

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Core-PWA#4405]
remove fixed width from call windows. use either flex or grid

**Comment by stavares843** [comment]
https://github.com/Satellite-im/Core-PWA/pull/4468

**Comment by stavares843** [comment]
> Automation for Jira commented in Jira:

The linked issue -https://satellite-im.atlassian.net/browse/AP-2213#icft=AP-2213has been resolved

**Comment by josephmcg** [comment]
closing this, Jason is going to implement a different way
