### ISSUE TITLE
AP-2256: improve PhantomAdapter.test.ts

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Core-PWA#4501]

**Comment by stavares843** [comment]
> Sara Tavares commented in Jira:

@Andre Pramadityabefore working on this talk to Nicholas to see what in there he needs help with coverage for

**Comment by stavares843** [comment]
> Sara Tavares commented in Jira:

reporter: Sara Tavares

**Comment by WanderingHogan** [comment]
@drepram I randomly chose this ticket to see what kind of info Github adds
