### ISSUE TITLE
Self name missing on dev

### ISSUE THREAD

**Issue by WanderingHogan** [Satellite-im/Core-PWA#4536]
![Screen Shot 2022-08-30 at 10 34 09 AM](https://user-images.githubusercontent.com/2993032/187491595-210074f0-f978-4bf8-9e9b-60384fd90a65.png)

**Comment by WanderingHogan** [comment]
Make sure to pull current dev down

**Comment by Jekrimo** [comment]
Do we have any more details for this one? I can't seem to replicate it, ie, always has the username for me.

**Comment by stavares843** [comment]
i was able to reproduce, on https://satellite-dev.on.fleek.co/#/ doing a new user would show as hogan's screenshot

**Comment by Jekrimo** [comment]
OHHHH, so it's only happening on the dev build and not locally, awesome. Gratci!

**Comment by josephmcg** [comment]
was an issue of profile getting set incorrectly, fixed here
https://github.com/Satellite-im/Core-PWA/pull/4541
