### ISSUE TITLE
Centralized place in app to manage permissions - Screenshare Help Toggle

### ISSUE THREAD

**Issue by WanderingHogan** [Satellite-im/Core-PWA#4557]
Make the screen share OS dependent. Hide that part of permissions if the OS doesn't require any special overrides.

There are methods available in app already to detect of it's a mac - in the help modal show basic instructions how to enable screen sharing in the browser (i think it's called screen recording), and let them know it will require a browser restart

**Comment by stavares843** [comment]
already done
