### ISSUE TITLE
Toolbar details missing

### ISSUE THREAD

**Issue by aewing** [Satellite-im/Core-PWA#4578]
navigation/toolbar/Toolbar.html references `details` (the details of the user/group related to the active conversation), but it is missing in `Toolbar.vue`, causing errors in the console and causing the user avatar circle not to render.

![toolbar-vue](https://user-images.githubusercontent.com/5033161/188015915-3a7ba455-f883-414f-943c-36b217311d0f.png)

**Comment by josephmcg** [comment]
uiUserState got me like 
https://c.tenor.com/sgof3MXQFOgAAAAC/snip-snap-michael-scott.gif

**Comment by aewing** [comment]
Vue reactivity got me like

**Comment by aewing** [comment]
(I went back and forth on this trying to make sense of the reactivity bug in the sidebar)
