### ISSUE TITLE
Calling includes extra box for previous call

### ISSUE THREAD

**Issue by WanderingHogan** [Satellite-im/Core-PWA#4646]
![Screen Shot 2022-09-07 at 9 45 39 AM](https://user-images.githubusercontent.com/2993032/188921996-58aff6f8-76de-4ea2-8797-0e4ed1313bd5.png)

I was in a call with kevin, then i went and called Sheldon and there must be an array that doesn't get cleared out

**Comment by WanderingHogan** [comment]
Jason believes this might be a webrtc thing, but has not had a chance to dig into it

**Comment by jasonwoodland** [comment]
@WanderingHogan Yep, we can probably just clear the `webRTC.state.streamMuted` object when starting/ending a call

**Comment by WanderingHogan** [comment]
![unknown](https://user-images.githubusercontent.com/2993032/189059136-d2c24a68-721f-4115-bbd8-b4b92a9b9353.png)

**Comment by WanderingHogan** [comment]
@JustZacca when there are 2 users, we expect to see 2 boxes, unless one of them is screensharing, in which case it looks like the screenshare and user box are showing
