### ISSUE TITLE
Detect if core is open on multiple tabs of the same browser

### ISSUE THREAD

**Issue by WanderingHogan** [Satellite-im/Core-PWA#4706]
We need a way to detect if the user is trying to load the same site in multiple tabs. Not sure how to do it, or what the best feeling would be for users - do you want to block it from loading and have a warning, do you want to refresh the other tab they have open so it disconnects, etc? Experiment and find a good way to prevent the connection to the sync nodes from getting all wonky.

**Comment by stavares843** [comment]
<img width="1023" alt="Captura de ecrã 2022-09-23, às 01 08 47" src="https://user-images.githubusercontent.com/29093946/191871833-9ebe58b0-d9dc-499f-9fd9-01513b02c236.png">


whatsapp web asks like

you have this open in more tabs you wanna use here or on the other?

and then buttons use here/not use here
