### ISSUE TITLE
attach width and height to chat images

### ISSUE THREAD

**Issue by josephmcg** [Satellite-im/Core-PWA#4728]
scroll is funky when you initially open a chat because these images load in afterward.

We need to show placeholders with the same height and width to keep the same layout

There was some previous work on this here
https://github.com/Satellite-im/Core-PWA/tree/AP-1731

**Comment by ThomBos** [comment]
this issue seems related to messages load.
once you start scrolling up it loads previous messages and images, that's why this happens... might try to gradually increase size (starting from 0 height to its natural height) of just loaded images

**Comment by josephmcg** [comment]
marking as backlog because scroll is now properly locked to the bottom, even after image load. maybe this would be nice someday if images are in the viewport when you load in
