### ISSUE TITLE
refresh loses messages in iridium

### ISSUE THREAD

**Issue by WanderingHogan** [Satellite-im/Core-PWA#4751]
send a bunch back and forth, reload, some messages are missing, it doesn't seem to want to keep anything after a certain point

**Comment by WanderingHogan** [comment]
I think this might be related to failures when uploading files - around the time file uploads stop working, a refresh sets us back to around that time with messages.

@pavlzk Can you dig in to this? Can you see if it's a file size issue, file name issue of upload, something with the upload service, or something with how iridium handles uploads?

I will send you an env you can use for your iridium

**Comment by stavares843** [comment]
seems no longer happens
