### ISSUE TITLE
refactor - typing status

### ISSUE THREAD

**Issue by josephmcg** [Satellite-im/Core-PWA#4752]
consider using a Set instead of an array so we don't have duplicates. I haven't noticed any bugs with the current implementation, but this would be more bug-proof for sure.

**Comment by molimauro** [comment]
it was an object some times ago 😓

**Comment by josephmcg** [comment]
Oh it is an object in some capacity. Key value pair of conversationId : array of dids. It works well, just a set would work even better than an array

**Comment by molimauro** [comment]
yeah it's the array part that was an object, but yes let's go with a set

**Comment by josephmcg** [comment]
need to wait til nuxt3 upgrade
