### ISSUE TITLE
Offline messages not always received

### ISSUE THREAD

**Issue by WanderingHogan** [Satellite-im/Core-PWA#4762]
https://user-images.githubusercontent.com/2993032/189989531-73618a81-380e-4464-9875-6b5be9cd2f5f.mov

**Comment by aewing** [comment]
we can solve this either of two ways:
1. we send the `sync/fetch` to _all_ nodes when we connect to them
2. we sync the `sync` table to every table like we do with the `pins`

1 is the easiest and probably the best solution, but if you connect and one of the sync nodes is offline, you won't receive any offline sync messages from that node until you restart your browser, so we might want to consider baking it into `p2p.ts` so we send the `sync/fetch` request to every node in the `onPeerConnect` handler.
