### ISSUE TITLE
disable editing of username

### ISSUE THREAD

**Issue by nathan-power** [Satellite-im/Core-PWA#4802]
- Changed account ID's do not work in search. Disable username editing until this is resolved.

**Comment by stavares843** [comment]
agree also besides that when we edit the username doesn't properly update on both sides, the user that changed the name vs the other user that has that one added

**Comment by nathan-power** [comment]
> agree also besides that when we edit the username doesn't properly update on both sides, the user that changed the name vs the other user that has that one added

Didn't know this
Thanks for the information

**Comment by stavares843** [comment]
i noticed that yesterday when chatting with phil and hogan, phil changed his name and wasn't changed on my side, i changed my name and updated on hogan's side but not on mine even after reloading
