### ISSUE TITLE
typing indicator

### ISSUE THREAD

**Issue by molimauro** [Satellite-im/Core-PWA#4834]
I think there are some problems with the typing indicator:

![image](https://user-images.githubusercontent.com/50131258/190415803-ec9b7364-ab81-4c52-b172-8b732c45d243.png)

Dont know how but this happened on 1to1 chat

**Comment by stavares843** [comment]
also saw that bug now on dev lol while on chat with Phil

<img width="425" alt="Captura de ecrã 2022-09-15, às 17 30 19" src="https://user-images.githubusercontent.com/29093946/190458189-f019f0bc-6561-44dc-814e-e241c1ae52e0.png">

**Comment by stavares843** [comment]
other bug related with the typing indicator is also when no one is typing, user already made other account and all still shows as typing

my account

![image](https://user-images.githubusercontent.com/29093946/190458831-402a9d9f-aaf1-4ed8-87e4-a4b06778ec8b.png)

phil already using other account but still showing as typing above

![image](https://user-images.githubusercontent.com/29093946/190458872-aa28475f-f38f-4443-bced-d2c9093b28d8.png)

**Comment by molimauro** [comment]
Can you check if those are still present here?

**Comment by stavares843** [comment]
gonna check on your PR 🔨
