### ISSUE TITLE
Group chat - invisible member on group list + undefined push + internal missing text on chat message

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Core-PWA#4852]
STR:
- If Phil is added as my friend and he adds a group with me Phil and Hogan and Hogan is not added as my friend will appear like this

<img width="1090" alt="Captura de ecrã 2022-09-16, às 01 55 43" src="https://user-images.githubusercontent.com/29093946/190535410-b79e6c4a-df01-4107-ab84-4ac51a63b4c9.png">

- the member that is not added on my friends list appears as invisible

then

the push’s will appear as undefined

![image](https://user-images.githubusercontent.com/29093946/190535521-95316c90-c79e-4b01-810a-a45be855313b.png)

and the messages will appear as internal missing text

![image](https://user-images.githubusercontent.com/29093946/190535541-5aeee4b1-05e6-4614-a054-25433bb9e2c7.png)

**Comment by josephmcg** [comment]
i can't reproduce this locally, but we can at least make it fail gracefully. like add an 'unknown' instead of no user information

**Comment by molimauro** [comment]
This is definitely because the searchPeer fails or times out when creating a group, not a frontend bug i guess unfortunately
