### ISSUE TITLE
User A calls User B then hangsup User B is left with Call Modal 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Core-PWA#4862]
**Issue:** If user A calls User B and then hangsup before User B gets a chance to answer, User B will be left with the Call Modal open when the call has already ended up User A 

**How to replicate:** 
1. Call User B 
2. Hangup before they answer 
3. Notice User B still has call modal open 

**Screen recording:**

https://user-images.githubusercontent.com/93608357/190551988-302a8037-609d-42c5-a815-66e4cc87dc6a.mov

**Comment by molimauro** [comment]
Is this still valid?
