### ISSUE TITLE
Files - only show if they have the safer signature

### ISSUE THREAD

**Issue by WanderingHogan** [Satellite-im/Core-PWA#4930]
In iridium when you get a file to show to the end user - im messages only show if it has the safer signature, indicated it was reviewed and deemed not CSAM by SAfer

**Comment by WanderingHogan** [comment]
blocked by Mu's safer work right now

**Comment by josephmcg** [comment]
right now it doesn't send anything if it fails the scan

https://github.com/Satellite-im/Core-PWA/blob/8b6bb252144797e7c33e2e78b1f2e05b4e6e566b/libraries/Iridium/chat/ChatManager.ts#L648-L671
