### ISSUE TITLE
Add timeout to 'linking satellites'

### ISSUE THREAD

**Issue by WanderingHogan** [Satellite-im/Core-PWA#4933]
Add a timeout to linking satellites that kicks the user back to the sign in page after 30 seconds with an error message on the sign in page that says something like 'We were unable to log you in, please try again soon or create a new account.

Also investigate root cause of issue, Sheldon and Drew are debugging

**Comment by stavares843** [comment]
can we reuse the same logic we did [here](https://github.com/Satellite-im/Core-PWA/pull/3062) instead? when we were using solana, we added a modal that would appear after 30s, can we reuse that but for the nodes timeout?
