### ISSUE TITLE
Safari - no chats are displayed on sidebar

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Core-PWA#4937]
STR:
- Go to Safari
- Add a friend
- No chat appears on sidebar

works fine on Chrome

<img width="1338" alt="Captura de ecrã 2022-09-19, às 23 39 51" src="https://user-images.githubusercontent.com/29093946/191131843-659537f4-f00c-47de-860e-bebc95bc1b4a.png">

**Comment by nathan-power** [comment]
Hi @stavares843, have looked into it but can't replicate. It seems to be working fine on both my local version and core, but it's not working on your end?

**Comment by stavares843** [comment]
it never works for me in either fleek's from any PR's or hippo or core

@phillsatellite is this the same for you?

**Comment by stavares843** [comment]
k is good for phil


![image](https://user-images.githubusercontent.com/29093946/191871010-2eb315b5-27f3-42d1-9a83-fbcb6f32d518.png)


but on my side still happens

![image](https://user-images.gitubusercontent.com/29093946/191871022-5b84d951-f4a5-4149-9a58-3c17b361055f.png)


@molimauro do you have this bug on safari?

**Comment by molimauro** [comment]
No i dont. @stavares843 which Safari version do you have? Im on 16.0. But i dont see a real cause why that should work on Chrome and not on Safari 😧

**Comment by stavares843** [comment]
15 😂
