### ISSUE TITLE
disable chatbar while subscribing to iridium

### ISSUE THREAD

**Issue by molimauro** [Satellite-im/Core-PWA#4988]
disable the chatbar (and related controls) and put a "Connecting..." instead of the "Speak freely..." placeholder while we're subscribing to iridium

**Comment by josephmcg** [comment]
The flag we're using for this should probably be changed. It's checking for iridium.chat.ready. That's fine for existing conversations, but messages get lost in new conversations because new the subscription isn't ready while iridium.chat.ready is true.

Probably an array of conversation id's

**Comment by josephmcg** [comment]
i experimented here, but it wasn't behaving as I expected. gonna work on some other stuff instead
4988-draft

**Comment by josephmcg** [comment]
1 more note about ux regarding this task.. I think adding a note below the footer would be better than disabling the chatbar. This way the user can at least type and draft a message while waiting

**Comment by molimauro** [comment]
> i experimented here, but it wasn't behaving as I expected. gonna work on some other stuff instead [4988-draft](https://github.com/Satellite-im/Core-PWA/tree/4988-draft?rgh-link-date=2022-09-26T02%3A14%3A56Z)

what was wrong?

**Comment by molimauro** [comment]
Problems arise when one of the two peers is online but not connected and the other sends a message. This message is not treated as offline by the sync node and is not delivered
