### ISSUE TITLE
files - uploading files on files doesn't work

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Core-PWA#4992]
STR:
- go to files
- upload any file

![image](https://user-images.githubusercontent.com/29093946/191827706-1ec3fe38-35f1-4025-9751-c9a97b93b29f.png)

never uploads and returns error saying the file can't be uploaded

**Comment by josephmcg** [comment]
ah yeah ChatManager got some syntax updates that weren't applied here as well. I may break out the upload into a utility
