### ISSUE TITLE
Add friends doesn't always work

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Core-PWA#4996]
STR:
- add a friend

sometimes either doesn't find the friend or just keeps loading and timeouts on the request

<img width="954" alt="Captura de ecrã 2022-09-23, às 00 28 10" src="https://user-images.githubusercontent.com/29093946/191868526-9f139551-ac48-41c0-b1f3-6f91df8a1b2a.png">

https://user-images.githubusercontent.com/29093946/191867891-5b5cf299-316a-4865-9817-ec3ae77a95cc.mov

it happens since last week 

also happens on core, including various users on the community that also reached out about this bug

happens on both fleek's on PR's and also hippo env

primary sync node - NY

**Comment by molimauro** [comment]
core seems not updated

**Comment by stavares843** [comment]
still happens

we need to refresh the user we wanna add to be able to add
