### ISSUE TITLE
restore "you're viewing older messages" in chat

### ISSUE THREAD

**Issue by molimauro** [Satellite-im/Core-PWA#5001]
there are already state and mutations in place like `showOlderMessagesInfo` in the `ui` state

this:
![image](https://user-images.githubusercontent.com/50131258/191982808-6a4ec3f8-0cd3-4182-9c90-3a0db4f44ff3.png)

**Comment by stavares843** [comment]
neat 🎉

**Comment by josephmcg** [comment]
resolved https://github.com/Satellite-im/Core-PWA/pull/5098
