### ISSUE TITLE
allow up arrow in chatbar without forcing edit

### ISSUE THREAD

**Issue by josephmcg** [Satellite-im/Core-PWA#5008]
from this PR https://github.com/Satellite-im/Core-PWA/pull/4986

We need to allow users to press the up arrow to navigate a multi-line message draft

try typing a message like this and hitting up
![image](https://user-images.githubusercontent.com/33670767/192173677-216312e1-5412-45ef-80db-8c9e3990a665.png)

Also wondering, whats the advantage of doing keyup here rather than using the existing keydown function?

**Comment by molimauro** [comment]
Oh nice catch! No value added, in my mind i had the keyup dont know why. I'll switch that for sure!
