### ISSUE TITLE
Chat - if you send messages without internet, they appear on sidebar but not in the chat

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Core-PWA#5093]
STR:
- remove internet
- go to chat
- send messages
- they appear on the sidebar but not on the chat itself
- if you reload, with internet, they appear

![image](https://user-images.githubusercontent.com/29093946/193088303-f576edc2-e37b-4f60-b02a-4993de8ae47f.png)

Chrome, macOS

**Comment by molimauro** [comment]
On my side it appears in the chat as well 😮
