### ISSUE TITLE
Friends - if you delete the friend and add the same friend again, doesn't add

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Core-PWA#5112]
STR:
- add a friend
- remove
- add the same friend again
- try to accept that request
- just refresh's the request and never accepts, returns a error saying it's already a friend and appears as a friend on the same of the user that sent the request as well

env - hippo, dev

always reproducible

https://user-images.githubusercontent.com/29093946/193430423-ca8baa6e-f916-4417-bfea-e2671b931b1d.mov

Chrome, macOS

**Comment by molimauro** [comment]
cant reproduce, do you have a full video? :)

**Comment by stavares843** [comment]
can't reproduce as well

@phillsatellite can you try it as well and if happens for you reopen the ticket pls
