### ISSUE TITLE
Add @ mention functionality to chatbar

### ISSUE THREAD

**Issue by jasonwoodland** [Satellite-im/Core-PWA#5151]

**Comment by molimauro** [comment]
Let me know if you need any clarification, you are going to mess with the Markdown.ts (for adding the parsing rule for mentions) and with the Cursor.ts for the cursor position

**Comment by jasonwoodland** [comment]
@molimauro I'm going to leave the markdown side of things for now and just autocomplete the plaintext. Happy to take a look at it with you later so we can get rich text insertion!
