### ISSUE TITLE
autocomplete - the satellite avatar not in the right size

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Core-PWA#5184]
![image](https://user-images.githubusercontent.com/29093946/194593848-505c2c5e-0639-4297-acac-da37d1b1f4b2.png)

the satellite avatar doesn't seem in the right size

if you compare with other places, is not as small

https://github.com/Satellite-im/Core-PWA/pull/5163#pullrequestreview-1134708708

**Comment by molimauro** [comment]
This is fine, it makes sense being smaller
