### ISSUE TITLE
autocomplete - remove ""

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Core-PWA#5189]
<img width="364" alt="Captura de ecrã 2022-10-07, às 16 29 48" src="https://user-images.githubusercontent.com/29093946/194591604-0e9257d4-3be2-47cd-a1d7-16d096658014.png">

do we need this "" before we start to search?

**Comment by stavares843** [comment]
cc @molimauro what do you think?

**Comment by molimauro** [comment]
We can completely ditch the "" even when there is some letters
