### ISSUE TITLE
Native Mobile - Update app icons to what Uplink is using

### ISSUE THREAD

**Issue by WanderingHogan** [Satellite-im/Core-PWA#5197]

**Comment by stavares843** [comment]
https://github.com/Satellite-im/Core-PWA/pull/5190/commits/71f80d0eb03217377e45e26620595e5d4cd4dd96

vs

https://github.com/Satellite-im/Uplink/blob/dev/ios/Runner/Assets.xcassets/AppIcon.appiconset/icon_60pt%403x.png

i believe the app icons are already the same
