### ISSUE TITLE
Sign up - focus trap error

### ISSUE THREAD

**Issue by stavares843** [Satellite-im/Core-PWA#5296]
STR:
- sign up
- you get the focus trap error in console below

<img width="1123" alt="Captura de ecrã 2022-10-17, às 13 13 06" src="https://user-images.githubusercontent.com/29093946/196175366-1d2618f7-2f39-4f39-accd-7b71216a8199.png">

Chrome, macOS

**Comment by josephmcg** [comment]
which branch is this? dev should be ok. I added a conditional check to fix this here
https://github.com/Satellite-im/Core-PWA/pull/5231

**Comment by stavares843** [comment]
was on this [PR](https://github.com/Satellite-im/Core-PWA/pull/5291) but then hippo was the same, and added the ticket

**Comment by stavares843** [comment]
i can test again now that one is merged 🔨

**Comment by stavares843** [comment]
still happens

shady
